export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR ERRORS';



/** watchlist types  **/
export const SET_RISK_PERCENT = "SET_RISK_PERCENT";
export const SET_PORTFOLIO_VALUE = "SET_PORTFOLIO_VALUE"
export const CALCULATE_RISK = "CALCULATE_RISK" 
export const RESET_CALCULATOR = "RESET_CALCULATOR"
export const CALCULATOR_CHANGE = "CALCULATOR_CHANGE"
export const ADD_WATCHLIST_ITEM = "ADD_WATCHLIST_ITEM";
export const DELETE_WATCH_ITEM = "DELETE_WATCH_ITEM";
export const GET_TOTAL_PORTFOLIO = "GET_TOTAL_PORTFOLIO";
export const GET_RISK_PERCENT = "GET_RISK_PERCENT"